export const MOVE_PARTICLE = 'MOVE_PARTICLE';
export const PARTICLE_MOVE_REQUESTED = 'PARTICLE_MOVE_REQUESTED';
export const ADD_PARTICLE = 'ADD_PARTICLE';
export const DELETE_PARTICLE = 'DELETE_PARTICLE';
